spring:
  datasource:
    # 1. URL 格式完全不同 (記得改 IP 和 databaseName)
    # 1.AzureDB
#    url: jdbc:sqlserver://rocky-blog.database.windows.net:1433;databaseName=free-sql-db-8788767;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    username: rockyDB@rocky-blog
#    password: 1qaz@WSX

    # 1.改本機的 MS SQL
    url: jdbc:sqlserver://localhost:1433;databaseName=blog_db;encrypt=false;trustServerCertificate=true
    username: sa
    password: YourStrongPassword123

    # 2. Driver 類別名稱換了
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    properties:
      hibernate:
        # 4. 告訴 Hibernate 改說 MS SQL 的方言
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    hibernate:
      # 開發階段可以用 update，正式環境建議 validate
      ddl-auto: update
# 自定義的 JWT 設定
jwt:
  # 密鑰 (這串字串要夠長，至少 32 個字元，不然程式會報錯說不安全)
  secret: MySuperSecretKeyForSpringSecurityTutorial2026
  # 過期時間 (毫秒)，這裡設為 24 小時 (86400000)
  expiration: 86400000