spring:
  datasource:
    # 1. URL 格式完全不同 (記得改 IP 和 databaseName)
    # JDBC URL 格式：jdbc:postgresql://<host>:<port>/<database>
    url: jdbc:postgresql://ep-sweet-hat-a1zth8g8.ap-southeast-1.aws.neon.tech/rockydb?sslmode=require&channel_binding=require
    # 2. Driver 類別名稱換了
    driver-class-name: org.postgresql.Driver
    # 3. 這裡要填入您的 Postgresql 帳號
    username: neondb_owner
    # 3. 這裡要填入「新的」加密密碼（請用 JasyptTest 重新算一組）
    password: npg_zNVKQxc80taB

  jpa:
    properties:
      hibernate:
        # 4. 告訴 Hibernate 改說 MS SQL 的方言 (註：圖中註解寫 MS SQL 但值是 PostgreSQL)
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      # 開發階段可以用 update，正式環境建議 validate
      ddl-auto: update

# 自定義的 JWT 設定
jwt:
  # 密鑰（這串字串要夠長，至少 32 個字元，不然程式會報錯說不安全）
  secret: MySuperSecretKeyForSpringSecurityTutorial2026
  # 過期時間（毫秒），這裡設為 24 小時 (86400000)
  expiration: 86400000