spring:
  datasource:
    # 這裡的 url 格式：jdbc:postgresql://[您的Host]/[您的DB名稱]?sslmode=require
    # 注意：Neon 強制要求 SSL，所以後面一定要加 ?sslmode=require
    url: jdbc:postgresql://ep-cold-breeze-a16jmu1p.ap-southeast-1.aws.neon.tech/BlogApiDB?sslmode=require&channel_binding=require
    username: neondb_owner # 您的 Neon 帳號
    password: ENC(5cfMUAiNIO/Ezhk13+S4i8uQgSY05RdrcUI7JdvWW1Eoa7WlyIsmxeJurdxJ/J1TNcCC22rFYndlqlfXY0lhkw==) # 您的 Neon 密碼
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Dialect 改成 PostgreSQL
        dialect: org.hibernate.dialect.PostgreSQLDialect
# 自定義的 JWT 設定
jwt:
  # 密鑰 (這串字串要夠長，至少 32 個字元，不然程式會報錯說不安全)
  secret: MySuperSecretKeyForSpringSecurityTutorial2026
  # 過期時間 (毫秒)，這裡設為 24 小時 (86400000)
  expiration: 86400000